### ISSUE TITLE
Error code while attempting to run (in Gradio)

### ISSUE THREAD

**Issue by TheBomberCaptain** [resemble-ai/chatterbox#119]
I've tried to run this with both a reference audio file and no reference audio, but I keep getting the same error:

Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

Could anyone help me with this?

**Comment by AznamirWoW** [comment]
If CUDA is not available the gradio tts script should be setting DEVICE value to "cpu" instead of "cuda". I did test the generation in either mode and it works fine. What's your GPU and installed torch version?

**Comment by fellowricky** [comment]
I'm also getting the same error, I'm using an AMD 6950xt with ROCm installed

**Comment by TheBomberCaptain** [comment]
@fellowricky I don't know if this will fix your version, but how I fixed mine is by uninstalling the current version of torch and reinstalling the one with cuda. that seemed to fix it. I used chatgpt to guide be through it

**Comment by Goldiserv** [comment]
I got this error too (AMD GPU).
Attached gradio_tts_app_v2.py.md fixed it for me. Remove .md to use.
I also added the used seed as an output which heavily impacts the voice output 'personality'.

[gradio_tts_app_v2.py.md](https://github.com/user-attachments/files/20620430/gradio_tts_app_v2.py.md)

Looks like some AMD users have figured out how to use ChatterBox here: https://github.com/resemble-ai/chatterbox/issues/52

**Comment by JeremyCCHsu** [comment]
Thanks for the disucssion. We can't reproduce the issue on our side. We don't support AMD GPUs, but you may find #52 helpful.
