### ISSUE TITLE
NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.

### ISSUE THREAD

**Issue by wonder75** [resemble-ai/chatterbox#344]
Running the usage example script fails after a fresh installation.

Create python venv
~/.pyenv/versions/3.11.13/bin/python -m venv venv

Activate venv
source ./venv/bin/activate

install 
pip install chatterbox-tts

Run usage example script from project page
python ./test.py

This fails with:

/home/a/ai/chatterbox/venv/lib/python3.11/site-packages/torch/cuda/__init__.py:235: UserWarning: 
NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
Traceback (most recent call last):
  File "/home/a/ai/chatterbox/./test.py", line 6, in <module>
    model = ChatterboxTTS.from_pretrained(device="cuda")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a/ai/chatterbox/venv/lib/python3.11/site-packages/chatterbox/tts.py", line 180, in from_pretrained
    return cls.from_local(Path(local_path).parent, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a/ai/chatterbox/venv/lib/python3.11/site-packages/chatterbox/tts.py", line 142, in from_local
    ve.to(device).eval()
    ^^^^^^^^^^^^^
  File "/home/a/ai/chatterbox/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1343, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/a/ai/chatterbox/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 903, in _apply
    module._apply(fn)
  File "/home/a/ai/chatterbox/venv/lib/python3.11/site-packages/torch/nn/modules/rnn.py", line 290, in _apply
    self._init_flat_weights()
  File "/home/a/ai/chatterbox/venv/lib/python3.11/site-packages/torch/nn/modules/rnn.py", line 215, in _init_flat_weights
    self.flatten_parameters()
  File "/home/a/ai/chatterbox/venv/lib/python3.11/site-packages/torch/nn/modules/rnn.py", line 271, in flatten_parameters
    torch._cudnn_rnn_flatten_weight(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by spotshare-nick** [comment]
Somewhat think your issue is with PyTorch and not Chatterbox.  Might want to contact them.  You can also always install a specific version of PyTorch if needed.

**Comment by Nynxz** [comment]
I modified dependencies and got chatterbox working on my 50 series with Python3.11 & Linux

```
dependencies = [
    "numpy>=1.24.0,<1.26.0",
    "librosa==0.11.0",
    "s3tokenizer",
 +  "torch==2.9.0",
 +  "torchaudio==2.9.0",
 -  "torch==2.6.0",
 -  "torchaudio==2.6.0",
    "transformers==4.46.3",
    "diffusers==0.29.0",
    "resemble-perth==1.0.1",
    "conformer==0.3.2",
    "safetensors==0.5.3",
    "spacy-pkuseg",
    "pykakasi==2.3.0",
    "gradio==5.44.1",
 -  "russian-text-stresser @ git+https://github.com/Vuizur/add-stress-to-epub",
 +  "ffmpeg<8",
 +  "torchcodec",
]```

**Comment by ron-1986** [comment]
@Nynxz Thank you, that worked!

**Comment by diphr** [comment]
can you guide me how did you resolved it. @Nynxz  I'm new to local models and I'm learning along the way.
I have a rtx 5060ti with ubuntu. I got similiar issue like this. where did you paste the script @wonder75

**Comment by Nynxz** [comment]
Modify `pyproject.toml` with the changes from above
install the new requirements with pip.
Its the same install instructions as chatterbox, just with a modified pyproject.toml

I use Astral UV for my package manager
https://docs.astral.sh/uv/pip/packages/#installing-packages-from-files

**Comment by schlosrat** [comment]
@Nynxz, your instructions above may or may not work for people, but they're certainly on the right track! Thanks for sharing that.

For me, following those instructions did not work on a brand new system I just built, which has a 5070 Ti as the GPU. The issue I ran into, which I suspect others may also run into, is the CUDA version you get when following those instructions. With your instructions, you'll get a PyTorch install that may or may not be compatible with the CUDA you've got installed for your GPU.

Straight out of the box, I had CUDA 12.9 by default after a clean Windows 11 Pro install. After downloading the latest stable drivers from Nvidia, I've now got CUDA 13.0. The Nvidia drivers package can be found here: https://www.nvidia.com/en-us/drivers/details/257327/

You probably already know this, but in case others find this and don't, it's wise to check which version of CUDA you've got. One way to do this is by using the `nvidia-smi` command at a command prompt. Once you know that, you can head over to https://pytorch.org/get-started/previous-versions/ and find the right PyTorch for compatibility with the CUDA you've got.

PyTorch recommended this for v2.9.0 with CUDA 13.0
pip install torch==2.9.0 torchvision==0.24.0 torchaudio==2.9.0 --index-url https://download.pytorch.org/whl/cu130

All I needed to do was to uninstall torch, torchaudio, and torchcodec, then issue the pip command above, and I was able to make use of my 5070 ti with chatterbox-tts from this repo.

**Comment by pal1n** [comment]
<img width="1441" height="836" alt="Image" src="https://github.com/user-attachments/assets/a6f9b115-1d16-4212-99a6-b3c4239ee6b6" /> So i am relatively new to this, and came here looking to see if i could get my 5070 working with chatterbox like my rtx3060 did. However it's not as fast as i'd hoped it would be, but made up for  in stability in running 2 terminals(generations at the same time) over 427k word book. So thanks to all the comments her helping me getting chatterbox working with resemble/chatterbox

**Comment by gpetrov** [comment]
I updated to PyTorch nightly 1.28 as it has now SM 120 support and now chatterbox is using my Nvidia 5090 gpu

It utilizes actually only 30% of the gpu, and takes a 1-2 seconds per sentence to generate so any speedup tips are welcome
