### ISSUE TITLE
Constant errors when creating multiple audio files

### ISSUE THREAD

**Issue by lmoroney** [resemble-ai/chatterbox#72]
Working through a JSON file containing the content I want to turn into audio, and switching speakers as I do it.

I'm frequently getting errors like:
Error generating audio for narrator (part 32): CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

I haven't recompiled, just used the pip install version.

Any ideas on how to get around this (using GPUs in Google Colab)

**Comment by zeropointnine** [comment]
Just encountered this as well. Seemed to work perfectly with one voice clone, but on my second try with a different reference sound sample, I got this error on about 10% of the prompts I tried. 

Using torch 2.6.0+cu126, Python 3.12.

Also worth mentioning: That error was preceded by several printouts like this in the console:
`C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cuda\Indexing.cu:1422: block: [376,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.`

**Comment by TediPapajorgji** [comment]
> Working through a JSON file containing the content I want to turn into audio, and switching speakers as I do it.
> 
> I'm frequently getting errors like: Error generating audio for narrator (part 32): CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> I haven't recompiled, just used the pip install version.
> 
> Any ideas on how to get around this (using GPUs in Google Colab)

These may be VRAM out of memory exceptions. How much VRAM are you working with?




> Just encountered this as well. Seemed to work perfectly with one voice clone, but on my second try with a different reference sound sample, I got this error on about 10% of the prompts I tried.
> 
> Using torch 2.6.0+cu126, Python 3.12.
> 
> Also worth mentioning: That error was preceded by several printouts like this in the console: `C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cuda\Indexing.cu:1422: block: [376,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.`

Do you have examples of text and reference audios that you could share that cause this?

**Comment by zeropointnine** [comment]
The attached voice sample triggers the error about 10% of the time.  Forgot to mention, I'm using a 3080Ti (12GB VRAM). Interestingly, I can get the error to occur eventually by processing the same prompt in a loop:

```
model = ChatterboxTTS.from_pretrained(device="cuda")
for i in range(0, 100):
    wav = model.generate("You could say earnestly.", audio_prompt_path=r"C:\workspace\_voice source audio\emily-bauer-ish-2-c.wav")
    ta.save("test-2.wav", wav, model.sr)
```

[emily-bauer-ish-2-c.zip](https://github.com/user-attachments/files/20521407/emily-bauer-ish-2-c.zip)

**Comment by neshani** [comment]
I'm getting the same thing randomly. I was able to get one sample audiobook created, but all others fail with this error at random times. I've noticed that on the last failure it generated a segment up to 100% 1000/1000 then crashed. The segment that it crashed on only contained the word "Now", but the progress bar went up to 100% before failing.

Running a 3090 with 24 GB of VRAM.

**Comment by psdwizzard** [comment]
I am getting these too, I really cant wait to figure out what's causing them

**Comment by neshani** [comment]
I've noticed that it/s slowly decreases over time, then the crashes become consistent. I'll start my generations and it/s will be in the 45-35it/s range. Over the course of an hour or so, it/s will drop to 20-10it/s. Then the crashes happen. Starting a new generation does not reset the it/s. Restarting my docker container starts the sampling speeds around 40-30it/s. 

I've added some truncated logs. Not sure how useful they'll be. It seems like garbage is accumulating and causing crashes. 

NVIDIA-SMI 572.83 - Driver Version: 572.83 - CUDA Version: 12.8 (on a 3090)

[Logs.txt](https://github.com/user-attachments/files/20542276/Logs.txt)

**Comment by psdwizzard** [comment]
@neshani I'm getting really similar errors as well. I'll post my log below. Although mine's from a fork of this, which is designed for audiobooks. But I have a feeling we're doing something similar. I was going to implement a soft restart when that error comes up and have it continue because I can do that in my fork. But when I restart from that spot, I get the same error immediately with the same generation, which makes me think it's something else to do with the way cuda is being implemented in the model.


[log-longGen.txt](https://github.com/user-attachments/files/20542699/log-longGen.txt)

**Comment by fakerybakery** [comment]
+1 I am getting this too

**Comment by mmoody-vv** [comment]
Also getting the same error. Tried several different fixes before finding this issue.
First tried generating the model at the launch of the api.
Then tried explicitly cleaning out the VRAM after every generation.
Finally tried explicitly creating and deleting the model for every generation.
None of these resolved the issue.

**Comment by fakerybakery** [comment]
I think I may have found a fix but I will test to make sure it actually works before submitting a PR

**Comment by fakerybakery** [comment]
I think it works on my side but would love additional testing from people before submitting a PR.

If anyone would be willing to test, the code is here: https://github.com/fakerybakery/better-chatterbox/tree/fix-cuda-issue

(Make sure to checkout the `fix-cuda-issue` branch when testing locally)

**Comment by psdwizzard** [comment]
@fakerybakery I'll test this out tomorrow on my git for audiobook creation I want to see how well it does with the hitchhiker's guide. 

I really appreciate it.

**Comment by fakerybakery** [comment]
@psdwizzard Thanks!

Should be usable as a drop-in replacement for `chatterbox-tts`, installable using `pip`:

```
pip install "chatterbox-tts @ git+https://github.com/fakerybakery/better-chatterbox@fix-cuda-issue"
```

(Though might not work since your project is a fork)

**Comment by mmoody-vv** [comment]
@fakerybakery I tried it an it's working for me. One concern I have -- and I'm not a CUDA expert at all so this may be silly: it looks like this is working by removing "bad" tokens. Is there any concern that multiple generation is making "bad" tokens in the first place?

**Comment by fakerybakery** [comment]
Not a CUDA expert either 😅
Yes - this does remove invalid tokens. I think it’s not something inherently about there being multiple generations - I think there’s a small chance with each generation that it will generate invalid tokens and multiple generations simply gives more opportunity for this to appear

**Comment by psdwizzard** [comment]
All right, it looks like the CUDA issue has been resolved. I've been generating books all day and have not run into it again. thanks @fakerybakery

**Comment by neshani** [comment]
@fakerybakery the fix seems to be working. I've been running it for a few hours with no problems. The iterations per second are still decreasing. I'm going from low 40's it/s to low 20's it/s in about 350 segments. But at least it's not crashing! Thanks for this!

**Comment by fakerybakery** [comment]
> [@fakerybakery](https://github.com/fakerybakery) the fix seems to be working. I've been running it for a few hours with no problems. The iterations per second are still decreasing. I'm going from low 40's it/s to low 20's it/s in about 350 segments. But at least it's not crashing! Thanks for this!

Thanks for testing! The speed issue is interesting… this fix shouldn’t affect generation time 🤔

**Comment by fakerybakery** [comment]
If anyone wants to test this out locally, you can install the fix for now as a drop-in replacement for Chatterbox (until the PR is merged). Instructions [here](https://github.com/NeuralVox/chatterbox-server#installation).
