### ISSUE TITLE
RuntimeError: Deserialization Fails on CPU-Only Systems Due to CUDA Mapping in torch.load

### ISSUE THREAD

**Issue by krenax** [resemble-ai/chatterbox#96]
I encountered a RuntimeError when attempting to run ChatterboxTTS on a CPU-only system. The issue stems from attempting to deserialize a checkpoint intended for CUDA on a system where torch.cuda.is_available() is False.

Additionally, a UserWarning is issued regarding the deprecation of pkg_resources, which will be removed as early as November 2025.

``
/home/kre/chatterbox/venv/lib/python3.12/site-packages/perth/perth_net/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename
Traceback (most recent call last):
  File "/home/kre/chatterbox/e.py", line 5, in <module>
    model = ChatterboxTTS.from_pretrained(device="cpu")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kre/chatterbox/venv/lib/python3.12/site-packages/chatterbox/tts.py", line 163, in from_pretrained
    return cls.from_local(Path(local_path).parent, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kre/chatterbox/venv/lib/python3.12/site-packages/chatterbox/tts.py", line 136, in from_local
    t3_state = torch.load(ckpt_dir / "t3_cfg.pt")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kre/chatterbox/venv/lib/python3.12/site-packages/torch/serialization.py", line 1462, in load
    return _load(
           ^^^^^^
  File "/home/kre/chatterbox/venv/lib/python3.12/site-packages/torch/serialization.py", line 1964, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "/home/kre/chatterbox/venv/lib/python3.12/site-packages/torch/_weights_only_unpickler.py", line 512, in load
    self.append(self.persistent_load(pid))
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kre/chatterbox/venv/lib/python3.12/site-packages/torch/serialization.py", line 1928, in persistent_load
    typed_storage = load_tensor(
                    ^^^^^^^^^^^^
  File "/home/kre/chatterbox/venv/lib/python3.12/site-packages/torch/serialization.py", line 1900, in load_tensor
    wrap_storage=restore_location(storage, location),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kre/chatterbox/venv/lib/python3.12/site-packages/torch/serialization.py", line 693, in default_restore_location
    result = fn(storage, location)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kre/chatterbox/venv/lib/python3.12/site-packages/torch/serialization.py", line 631, in _deserialize
    device = _validate_device(location, backend_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kre/chatterbox/venv/lib/python3.12/site-packages/torch/serialization.py", line 600, in _validate_device
    raise RuntimeError(
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
``

**Comment by TeddyRuncorn** [comment]
Same for me, I'm on Windows running via Anaconda, seems to run, the interface loads but a few seconds later, the Runtime error occurs, same as yours, mine is line 600 in serialization.py within the Torch package '_validate_device'

**Comment by krenax** [comment]
My machine runs the example provided in the README.md and fails unexpectedly.

**Comment by DocTorOo-source** [comment]
I had the same issue but resolved it by installing : 
pip install torch==2.6.0+cu118 torchvision==0.21.0+cu118 torchaudio==2.6.0+cu118 --index-url https://download.pytorch.org/whl/cu118

pip install xformers==0.0.25

**Comment by DocTorOo-source** [comment]
for the deprecation warning, (I have not yet tested yet) but it shows that you would need to install : pip install peft

**Comment by krenax** [comment]
> I had the same issue but resolved it by installing : pip install torch==2.6.0+cu118 torchvision==0.21.0+cu118 torchaudio==2.6.0+cu118 --index-url https://download.pytorch.org/whl/cu118
> 
> pip install xformers==0.0.25

But this does not solve the problem for users with machines running solely on CPU.

**Comment by DocTorOo-source** [comment]
If no GPU, you are right. If the user has GPU, like i did and still got this if i just followed the step given in the repo i end up with the same issue, So i researched and found that the Python version i am using 3.12 was the issue and so I updated the pytorch and fixed the CUDA errors. I am now working on creating a docker image. so once done may be docker image can help everyone.

My GPU: RTX 3060 TI which is not that great, but I am able to generate audio (30 sec's) in approx. 3 min.(which i am still happy with as i am getting much better quality output and I am using Gradio's API endpoint to generate this in my automation).

**Comment by mahimairaja** [comment]
I had the same issue @krenax 

I fixed it using `Monkey Patch approach` for now, The issue issue needs to be handled from chatterbox package itself from torch version 

Here is the script

```py
import time
import torchaudio as ta
import torch
from chatterbox.tts import ChatterboxTTS

original_torch_load = torch.load

def patched_torch_load(f, map_location=None, **kwargs):
    if map_location is None:
        map_location = 'cpu'
    return original_torch_load(f, map_location=map_location, **kwargs)

torch.load = patched_torch_load


model = ChatterboxTTS.from_pretrained(device="cpu")
torch.load = original_torch_load

text = "Hello, This is Mahimai"

start_time = time.perf_counter_ns()
wav = model.generate(text)
end_time = time.perf_counter_ns()

ta.save("test-1.wav", wav, model.sr)

print(f"Time taken: {end_time - start_time} seconds")
```

Please update if it fixes for you, Thanks

**Comment by krenax** [comment]
> I had the same issue [@krenax](https://github.com/krenax)
> 
> I fixed it using `Monkey Patch approach` for now, The issue issue needs to be handled from chatterbox package itself from torch version
> 
> Here is the script
> 
> import time
> import torchaudio as ta
> import torch
> from chatterbox.tts import ChatterboxTTS
> 
> original_torch_load = torch.load
> 
> def patched_torch_load(f, map_location=None, **kwargs):
>     if map_location is None:
>         map_location = 'cpu'
>     return original_torch_load(f, map_location=map_location, **kwargs)
> 
> torch.load = patched_torch_load
> 
> 
> model = ChatterboxTTS.from_pretrained(device="cpu")
> torch.load = original_torch_load
> 
> text = "Hello, This is Mahimai"
> 
> start_time = time.perf_counter_ns()
> wav = model.generate(text)
> end_time = time.perf_counter_ns()
> 
> ta.save("test-1.wav", wav, model.sr)
> 
> print(f"Time taken: {end_time - start_time} seconds")
> 
> Please update if it fixes for you, Thanks

This resolved my issue. A pull-request from your side would be helpful to resolve this.

**Comment by oisilener1982** [comment]
> I had the same issue but resolved it by installing : pip install torch==2.6.0+cu118 torchvision==0.21.0+cu118 torchaudio==2.6.0+cu118 --index-url https://download.pytorch.org/whl/cu118
> 
> pip install xformers==0.0.25

Thanks. Its working
